import { ALL_WORLD_CUP_TEAMS } from './worldCup';

export interface TeamPreset {
  name: string;
  att: number;
  opp: number;
  def: number;
  color1: string;
  color2: string;
  league?: string;
  isFlag?: boolean;
  region?: string;
  tier?: number;
}

export const PRESETS: Record<string, TeamPreset[]> = {
  ES: [
    { name: 'Real Madrid', att: 5, opp: 5, def: 4, color1: '#ffffff', color2: '#1e3a8a', league: 'ES' },
    { name: 'FC Barcelona', att: 5, opp: 5, def: 4, color1: '#a71930', color2: '#004d98', league: 'ES' },
    { name: 'Atlético Madrid', att: 4, opp: 5, def: 4, color1: '#cb3524', color2: '#ffffff', league: 'ES' },
    { name: 'Athletic Club', att: 4, opp: 4, def: 4, color1: '#cb3524', color2: '#000000', league: 'ES' },
    { name: 'Villarreal CF', att: 5, opp: 4, def: 4, color1: '#facc15', color2: '#1e3a8a', league: 'ES' },
    { name: 'Real Sociedad', att: 4, opp: 4, def: 4, color1: '#004d98', color2: '#ffffff', league: 'ES' },
    { name: 'Real Betis', att: 4, opp: 5, def: 3, color1: '#16a34a', color2: '#ffffff', league: 'ES' },
    { name: 'Girona FC', att: 2, opp: 3, def: 3, color1: '#cb3524', color2: '#ffffff', league: 'ES' },
    { name: 'Celta Vigo', att: 3, opp: 5, def: 4, color1: '#87d3f8', color2: '#ffffff', league: 'ES' },
    { name: 'Valencia CF', att: 3, opp: 4, def: 4, color1: '#ffffff', color2: '#000000', league: 'ES' },
    { name: 'Sevilla FC', att: 4, opp: 4, def: 3, color1: '#ffffff', color2: '#cb3524', league: 'ES' },
    { name: 'Osasuna', att: 4, opp: 3, def: 4, color1: '#cb3524', color2: '#1e3a8a', league: 'ES' },
    { name: 'Getafe', att: 3, opp: 3, def: 4, color1: '#1e3a8a', color2: '#ffffff', league: 'ES' },
    { name: 'Mallorca', att: 2, opp: 3, def: 4, color1: '#cb3524', color2: '#000000', league: 'ES' },
    { name: 'Rayo Vallecano', att: 4, opp: 3, def: 4, color1: '#ffffff', color2: '#cb3524', league: 'ES' },
    { name: 'Elche CF', att: 3, opp: 3, def: 3, color1: '#ffffff', color2: '#006400', league: 'ES' },
    { name: 'Alavés', att: 3, opp: 4, def: 3, color1: '#1e3a8a', color2: '#ffffff', league: 'ES' },
    { name: 'Levante UD', att: 2, opp: 4, def: 3, color1: '#a71930', color2: '#004d98', league: 'ES' },
    { name: 'Real Oviedo', att: 2, opp: 2, def: 4, color1: '#00529f', color2: '#ffffff', league: 'ES' },
    { name: 'Espanyol', att: 4, opp: 3, def: 3, color1: '#004d98', color2: '#ffffff', league: 'ES' }
  ],
  IT: [
    { name: 'Inter Milan', att: 5, opp: 5, def: 4, color1: '#003399', color2: '#000000', league: 'IT' },
    { name: 'Atalanta', att: 4, opp: 5, def: 4, color1: '#1e71b8', color2: '#000000', league: 'IT' },
    { name: 'Napoli', att: 5, opp: 5, def: 4, color1: '#00bfff', color2: '#ffffff', league: 'IT' },
    { name: 'Juventus', att: 4, opp: 5, def: 4, color1: '#ffffff', color2: '#000000', league: 'IT' },
    { name: 'AC Milan', att: 5, opp: 4, def: 4, color1: '#fb090b', color2: '#000000', league: 'IT' },
    { name: 'AS Roma', att: 4, opp: 4, def: 4, color1: '#8e1f2f', color2: '#f0bc42', league: 'IT' },
    { name: 'Lazio', att: 4, opp: 3, def: 4, color1: '#87d3f8', color2: '#ffffff', league: 'IT' },
    { name: 'Fiorentina', att: 3, opp: 5, def: 4, color1: '#4b2e83', color2: '#ffffff', league: 'IT' },
    { name: 'Bologna', att: 4, opp: 5, def: 3, color1: '#a71930', color2: '#1e3a8a', league: 'IT' },
    { name: 'Torino', att: 4, opp: 4, def: 3, color1: '#8b0000', color2: '#ffffff', league: 'IT' },
    { name: 'Como', att: 3, opp: 4, def: 4, color1: '#1e3a8a', color2: '#ffffff', league: 'IT' },
    { name: 'Genoa', att: 3, opp: 4, def: 3, color1: '#a71930', color2: '#1e3a8a', league: 'IT' },
    { name: 'Udinese', att: 4, opp: 3, def: 4, color1: '#ffffff', color2: '#000000', league: 'IT' },
    { name: 'Parma', att: 4, opp: 3, def: 3, color1: '#ffffff', color2: '#000000', league: 'IT' },
    { name: 'Sassuolo', att: 3, opp: 3, def: 3, color1: '#000000', color2: '#00a650', league: 'IT' },
    { name: 'Cagliari', att: 3, opp: 3, def: 4, color1: '#a71930', color2: '#1e3a8a', league: 'IT' },
    { name: 'Pisa', att: 2, opp: 3, def: 4, color1: '#000000', color2: '#0033a0', league: 'IT' },
    { name: 'Verona', att: 2, opp: 3, def: 3, color1: '#facc15', color2: '#1e3a8a', league: 'IT' },
    { name: 'Lecce', att: 2, opp: 4, def: 3, color1: '#facc15', color2: '#cb3524', league: 'IT' },
    { name: 'Cremonese', att: 2, opp: 2, def: 4, color1: '#8b0000', color2: '#a9a9a9', league: 'IT' }
  ],
  EN: [
    { name: 'Manchester City', att: 5, opp: 5, def: 4, color1: '#6caee0', color2: '#ffffff', league: 'EN' },
    { name: 'Liverpool FC', att: 5, opp: 5, def: 4, color1: '#c8102e', color2: '#f6eb61', league: 'EN' },
    { name: 'Arsenal FC', att: 5, opp: 5, def: 4, color1: '#ef0107', color2: '#ffffff', league: 'EN' },
    { name: 'Aston Villa', att: 4, opp: 4, def: 4, color1: '#95bfe5', color2: '#670e36', league: 'EN' },
    { name: 'Chelsea FC', att: 5, opp: 4, def: 4, color1: '#034694', color2: '#ffffff', league: 'EN' },
    { name: 'Newcastle', att: 4, opp: 5, def: 4, color1: '#ffffff', color2: '#000000', league: 'EN' },
    { name: 'Tottenham', att: 4, opp: 5, def: 3, color1: '#ffffff', color2: '#132257', league: 'EN' },
    { name: 'Brighton', att: 3, opp: 5, def: 4, color1: '#0057b8', color2: '#ffffff', league: 'EN' },
    { name: 'Man United', att: 5, opp: 3, def: 3, color1: '#da291c', color2: '#fbe122', league: 'EN' },
    { name: 'Nottingham Forest', att: 3, opp: 4, def: 4, color1: '#cb3524', color2: '#ffffff', league: 'EN' },
    { name: 'Bournemouth', att: 4, opp: 4, def: 3, color1: '#cb3524', color2: '#000000', league: 'EN' },
    { name: 'Brentford', att: 4, opp: 3, def: 4, color1: '#cb3524', color2: '#ffffff', league: 'EN' },
    { name: 'Fulham', att: 3, opp: 3, def: 4, color1: '#ffffff', color2: '#000000', league: 'EN' },
    { name: 'Crystal Palace', att: 3, opp: 4, def: 3, color1: '#1e3a8a', color2: '#cb3524', league: 'EN' },
    { name: 'West Ham', att: 2, opp: 3, def: 4, color1: '#7a263a', color2: '#1bb1e7', league: 'EN' },
    { name: 'Everton', att: 4, opp: 3, def: 3, color1: '#003399', color2: '#ffffff', league: 'EN' },
    { name: 'Wolves', att: 2, opp: 3, def: 3, color1: '#facc15', color2: '#000000', league: 'EN' },
    { name: 'Leeds United', att: 3, opp: 3, def: 3, color1: '#ffffff', color2: '#1d428a', league: 'EN' },
    { name: 'Burnley', att: 2, opp: 2, def: 4, color1: '#6c1d45', color2: '#87ceeb', league: 'EN' },
    { name: 'Sunderland', att: 2, opp: 4, def: 3, color1: '#ff0000', color2: '#ffffff', league: 'EN' }
  ],
  NL: [ 
    { name: 'PSV Eindhoven', att: 4, opp: 4, def: 4, color1: '#ff0000', color2: '#ffffff', league: 'NL' },
    { name: 'Feyenoord', att: 4, opp: 5, def: 3, color1: '#ff0000', color2: '#ffffff', league: 'NL' },
    { name: 'Ajax', att: 4, opp: 3, def: 4, color1: '#ffffff', color2: '#ff0000', league: 'NL' },
    { name: 'AZ Alkmaar', att: 3, opp: 4, def: 4, color1: '#ff0000', color2: '#ffffff', league: 'NL' },
    { name: 'FC Twente', att: 4, opp: 4, def: 3, color1: '#ff0000', color2: '#ffffff', league: 'NL' },
    { name: 'Utrecht', att: 4, opp: 3, def: 4, color1: '#ff0000', color2: '#ffffff', league: 'NL' },
    { name: 'Sparta Rotterdam', att: 3, opp: 3, def: 3, color1: '#ff0000', color2: '#ffffff', league: 'NL' },
    { name: 'Go Ahead Eagles', att: 3, opp: 3, def: 4, color1: '#ff0000', color2: '#ffff00', league: 'NL' },
    { name: 'NEC Nijmegen', att: 4, opp: 3, def: 3, color1: '#ff0000', color2: '#000000', league: 'NL' },
    { name: 'Heerenveen', att: 2, opp: 4, def: 3, color1: '#0000ff', color2: '#ffffff', league: 'NL' },
    { name: 'Fortuna Sittard', att: 2, opp: 3, def: 4, color1: '#ffff00', color2: '#16a34a', league: 'NL' },
    { name: 'Heracles Almelo', att: 3, opp: 3, def: 2, color1: '#000000', color2: '#ffffff', league: 'NL' },
    { name: 'PEC Zwolle', att: 2, opp: 3, def: 3, color1: '#00bfff', color2: '#ffffff', league: 'NL' },
    { name: 'FC Volendam', att: 2, opp: 3, def: 3, color1: '#f5a12d', color2: '#000000', league: 'NL' },
    { name: 'Excelsior', att: 2, opp: 2, def: 4, color1: '#000000', color2: '#e30613', league: 'NL' },
    { name: 'SC Telstar', att: 2, opp: 2, def: 3, color1: '#ffffff', color2: '#0033a0', league: 'NL' },
    { name: 'Groningen', att: 3, opp: 4, def: 3, color1: '#16a34a', color2: '#ffffff', league: 'NL' },
    { name: 'NAC Breda', att: 3, opp: 2, def: 2, color1: '#ffff00', color2: '#000000', league: 'NL' }
  ],
  DE: [ 
    { name: 'Bayern Munich', att: 5, opp: 5, def: 4, color1: '#dc052d', color2: '#ffffff', league: 'DE' },
    { name: 'B. Leverkusen', att: 4, opp: 5, def: 4, color1: '#e32221', color2: '#000000', league: 'DE' },
    { name: 'B. Dortmund', att: 4, opp: 5, def: 4, color1: '#fde100', color2: '#000000', league: 'DE' },
    { name: 'RB Leipzig', att: 4, opp: 4, def: 4, color1: '#ffffff', color2: '#dd013f', league: 'DE' },
    { name: 'E. Frankfurt', att: 4, opp: 4, def: 4, color1: '#000000', color2: '#e32221', league: 'DE' },
    { name: 'VfB Stuttgart', att: 4, opp: 5, def: 3, color1: '#ffffff', color2: '#e32221', league: 'DE' },
    { name: 'SC Freiburg', att: 4, opp: 4, def: 4, color1: '#000000', color2: '#ffffff', league: 'DE' },
    { name: 'Mainz 05', att: 3, opp: 5, def: 4, color1: '#ed1c24', color2: '#ffffff', league: 'DE' },
    { name: 'Werder Bremen', att: 3, opp: 4, def: 4, color1: '#1d9053', color2: '#ffffff', league: 'DE' },
    { name: 'Wolfsburg', att: 3, opp: 3, def: 3, color1: '#009d00', color2: '#ffffff', league: 'DE' },
    { name: 'M\'gladbach', att: 4, opp: 3, def: 4, color1: '#000000', color2: '#ffffff', league: 'DE' },
    { name: 'Augsburg', att: 3, opp: 3, def: 4, color1: '#ba3733', color2: '#ffffff', league: 'DE' },
    { name: 'Union Berlin', att: 4, opp: 3, def: 3, color1: '#d71920', color2: '#f6d800', league: 'DE' },
    { name: 'FC Köln', att: 3, opp: 4, def: 3, color1: '#e30613', color2: '#ffffff', league: 'DE' },
    { name: 'Hoffenheim', att: 2, opp: 4, def: 3, color1: '#004f9f', color2: '#ffffff', league: 'DE' },
    { name: 'Hamburger SV', att: 2, opp: 3, def: 4, color1: '#ffffff', color2: '#0033a0', league: 'DE' },
    { name: 'Heidenheim', att: 2, opp: 2, def: 4, color1: '#e2001a', color2: '#ffffff', league: 'DE' },
    { name: 'St. Pauli', att: 3, opp: 3, def: 2, color1: '#754b29', color2: '#ffffff', league: 'DE' }
  ],
  FR: [ 
    { name: 'PSG', att: 5, opp: 5, def: 4, color1: '#004170', color2: '#da291c', league: 'FR' },
    { name: 'AS Monaco', att: 4, opp: 4, def: 4, color1: '#e30613', color2: '#ffffff', league: 'FR' },
    { name: 'Marseille', att: 4, opp: 5, def: 3, color1: '#ffffff', color2: '#009dff', league: 'FR' },
    { name: 'Lille OSC', att: 4, opp: 5, def: 4, color1: '#e2001a', color2: '#002654', league: 'FR' },
    { name: 'Olympique Lyon', att: 4, opp: 5, def: 3, color1: '#ffffff', color2: '#da291c', league: 'FR' },
    { name: 'RC Lens', att: 4, opp: 4, def: 4, color1: '#ed1c24', color2: '#ffcc00', league: 'FR' },
    { name: 'OGC Nice', att: 4, opp: 4, def: 3, color1: '#000000', color2: '#e30613', league: 'FR' },
    { name: 'Brest', att: 4, opp: 3, def: 3, color1: '#e2001a', color2: '#ffffff', league: 'FR' },
    { name: 'Strasbourg', att: 4, opp: 4, def: 3, color1: '#00529f', color2: '#ffffff', league: 'FR' },
    { name: 'Stade Rennais', att: 3, opp: 3, def: 4, color1: '#e2001a', color2: '#000000', league: 'FR' },
    { name: 'Toulouse', att: 3, opp: 4, def: 4, color1: '#542f88', color2: '#ffffff', league: 'FR' },
    { name: 'FC Nantes', att: 4, opp: 3, def: 3, color1: '#fdf200', color2: '#006532', league: 'FR' },
    { name: 'FC Lorient', att: 2, opp: 3, def: 4, color1: '#f68712', color2: '#000000', league: 'FR' },
    { name: 'Paris FC', att: 2, opp: 4, def: 3, color1: '#0033a0', color2: '#ffffff', league: 'FR' },
    { name: 'AJ Auxerre', att: 3, opp: 4, def: 3, color1: '#ffffff', color2: '#00529f', league: 'FR' },
    { name: 'Le Havre', att: 2, opp: 2, def: 4, color1: '#00529f', color2: '#87ceeb', league: 'FR' },
    { name: 'FC Metz', att: 3, opp: 3, def: 3, color1: '#6c1d45', color2: '#ffffff', league: 'FR' },
    { name: 'Angers SCO', att: 3, opp: 3, def: 2, color1: '#000000', color2: '#ffffff', league: 'FR' }
  ],
  MI: [ 
    { name: 'Sporting CP', att: 5, opp: 4, def: 3, color1: '#006532', color2: '#ffffff', league: 'MI' },
    { name: 'Galatasaray', att: 4, opp: 4, def: 4, color1: '#a32638', color2: '#fdb913', league: 'MI' },
    { name: 'Celtic FC', att: 4, opp: 4, def: 4, color1: '#006532', color2: '#ffffff', league: 'MI' },
    { name: 'RB Salzburg', att: 4, opp: 4, def: 4, color1: '#ffffff', color2: '#e30613', league: 'MI' },
    { name: 'Slavia Praga', att: 4, opp: 4, def: 2, color1: '#e30613', color2: '#ffffff', league: 'MI' },
    { name: 'Shakhtar D.', att: 4, opp: 4, def: 3, color1: '#f68712', color2: '#000000', league: 'MI' },
    { name: 'Estrella Roja', att: 3, opp: 4, def: 4, color1: '#e30613', color2: '#ffffff', league: 'MI' },
    { name: 'Panathinaikos', att: 3, opp: 4, def: 4, color1: '#006532', color2: '#ffffff', league: 'MI' },
    { name: 'SC Braga', att: 4, opp: 3, def: 3, color1: '#e30613', color2: '#ffffff', league: 'MI' },
    { name: 'Beşiktaş', att: 3, opp: 4, def: 3, color1: '#000000', color2: '#ffffff', league: 'MI' },
    { name: 'Union SG', att: 3, opp: 4, def: 3, color1: '#fdd000', color2: '#0033a0', league: 'MI' },
    { name: 'FC Basel', att: 3, opp: 3, def: 4, color1: '#e30613', color2: '#0033a0', league: 'MI' },
    { name: 'Sturm Graz', att: 3, opp: 4, def: 3, color1: '#000000', color2: '#ffffff', league: 'MI' },
    { name: 'KRC Genk', att: 3, opp: 3, def: 3, color1: '#0033a0', color2: '#ffffff', league: 'MI' },
    { name: 'Dynamo Kyiv', att: 3, opp: 3, def: 3, color1: '#ffffff', color2: '#0033a0', league: 'MI' },
    { name: 'Vitória SC', att: 3, opp: 2, def: 3, color1: '#000000', color2: '#ffffff', league: 'MI' },
    { name: 'KAA Gent', att: 2, opp: 3, def: 3, color1: '#0033a0', color2: '#ffffff', league: 'MI' },
    { name: 'Malmö FF', att: 2, opp: 3, def: 3, color1: '#87ceeb', color2: '#ffffff', league: 'MI' }
  ],
  MB: [
    { name: 'Benfica', att: 4, opp: 4, def: 4, color1: '#e30613', color2: '#ffffff', league: 'MB' },
    { name: 'FC Porto', att: 4, opp: 4, def: 4, color1: '#003399', color2: '#ffffff', league: 'MB' },
    { name: 'Fenerbahçe', att: 4, opp: 5, def: 3, color1: '#0033a0', color2: '#fdb913', league: 'MB' },
    { name: 'Club Brugge', att: 3, opp: 5, def: 4, color1: '#0033a0', color2: '#000000', league: 'MB' },
    { name: 'Olympiacos', att: 4, opp: 4, def: 4, color1: '#e30613', color2: '#ffffff', league: 'MB' },
    { name: 'Dinamo Zagreb', att: 3, opp: 5, def: 4, color1: '#0033a0', color2: '#ffffff', league: 'MB' },
    { name: 'Rangers FC', att: 3, opp: 4, def: 4, color1: '#0033a0', color2: '#ffffff', league: 'MB' },
    { name: 'Sparta Praga', att: 3, opp: 4, def: 4, color1: '#a32638', color2: '#0033a0', league: 'MB' },
    { name: 'FC Copenhague', att: 4, opp: 3, def: 3, color1: '#ffffff', color2: '#0033a0', league: 'MB' },
    { name: 'PAOK', att: 3, opp: 4, def: 3, color1: '#000000', color2: '#ffffff', league: 'MB' },
    { name: 'AEK Athens', att: 3, opp: 4, def: 3, color1: '#fde100', color2: '#000000', league: 'MB' },
    { name: 'Young Boys', att: 3, opp: 4, def: 3, color1: '#ffd700', color2: '#000000', league: 'MB' },
    { name: 'Anderlecht', att: 3, opp: 3, def: 4, color1: '#542f88', color2: '#ffffff', league: 'MB' },
    { name: 'Trabzonspor', att: 3, opp: 3, def: 3, color1: '#8b0000', color2: '#87ceeb', league: 'MB' },
    { name: 'Bodo/Glimt', att: 3, opp: 3, def: 3, color1: '#ffff00', color2: '#000000', league: 'MB' },
    { name: 'Royal Antwerp', att: 2, opp: 3, def: 3, color1: '#e30613', color2: '#ffffff', league: 'MB' },
    { name: 'Aberdeen FC', att: 2, opp: 3, def: 3, color1: '#e30613', color2: '#ffffff', league: 'MB' },
    { name: 'Viktoria Plzen', att: 2, opp: 3, def: 3, color1: '#e30613', color2: '#0033a0', league: 'MB' }
  ],
  WC: ALL_WORLD_CUP_TEAMS.slice(0, 32)
};

export const PRESETS_2: Record<string, TeamPreset[]> = {
  ES: [
    { name: 'Almería', att: 2, opp: 3, def: 2, color1: '#e30613', color2: '#ffffff', league: 'ES' },
    { name: 'Cádiz CF', att: 1, opp: 3, def: 2, color1: '#fde100', color2: '#0000ff', league: 'ES' },
    { name: 'Granada CF', att: 2, opp: 2, def: 2, color1: '#c8102e', color2: '#ffffff', league: 'ES' },
    { name: 'SD Eibar', att: 3, opp: 2, def: 2, color1: '#a71930', color2: '#004d98', league: 'ES' },
    { name: 'Sporting Gijón', att: 2, opp: 2, def: 2, color1: '#e30613', color2: '#ffffff', league: 'ES' },
    { name: 'Valladolid', att: 1, opp: 3, def: 2, color1: '#ffffff', color2: '#951b81', league: 'ES' },
    { name: 'Las Palmas', att: 2, opp: 3, def: 1, color1: '#facc15', color2: '#1e3a8a', league: 'ES' },
    { name: 'Real Zaragoza', att: 1, opp: 3, def: 2, color1: '#ffffff', color2: '#00529f', league: 'ES' },
    { name: 'Racing Santander', att: 2, opp: 3, def: 2, color1: '#ffffff', color2: '#006400', league: 'ES' },
    { name: 'Leganés', att: 2, opp: 3, def: 1, color1: '#ffffff', color2: '#1e3a8a', league: 'ES' },
    { name: 'CD Tenerife', att: 1, opp: 3, def: 2, color1: '#ffffff', color2: '#00529f', league: 'ES' },
    { name: 'Burgos CF', att: 1, opp: 2, def: 3, color1: '#ffffff', color2: '#000000', league: 'ES' },
    { name: 'SD Huesca', att: 1, opp: 2, def: 3, color1: '#a71930', color2: '#004d98', league: 'ES' },
    { name: 'Málaga CF', att: 3, opp: 3, def: 3, color1: '#ffffff', color2: '#87ceeb', league: 'ES' },
    { name: 'Dep. La Coruña', att: 4, opp: 3, def: 3, color1: '#ffffff', color2: '#00529f', league: 'ES' },
    { name: 'Castellón', att: 2, opp: 3, def: 1, color1: '#000000', color2: '#ffffff', league: 'ES' },
    { name: 'Córdoba CF', att: 2, opp: 3, def: 1, color1: '#ffffff', color2: '#006400', league: 'ES' },
    { name: 'Albacete', att: 1, opp: 3, def: 2, color1: '#ffffff', color2: '#8b0000', league: 'ES' },
    { name: 'Mirandés', att: 2, opp: 3, def: 1, color1: '#e30613', color2: '#000000', league: 'ES' },
    { name: 'Eldense', att: 1, opp: 2, def: 3, color1: '#e30613', color2: '#0000ff', league: 'ES' }
  ],
  EN: [
    { name: 'Leicester City', att: 2, opp: 2, def: 2, color1: '#1e3a8a', color2: '#ffffff', league: 'EN' },
    { name: 'Ipswich Town', att: 2, opp: 3, def: 2, color1: '#1e3a8a', color2: '#ffffff', league: 'EN' },
    { name: 'Sheffield United', att: 2, opp: 3, def: 1, color1: '#ee2737', color2: '#ffffff', league: 'EN' },
    { name: 'Luton Town', att: 1, opp: 3, def: 2, color1: '#f78f1e', color2: '#000000', league: 'EN' },
    { name: 'West Bromwich', att: 2, opp: 2, def: 2, color1: '#002f68', color2: '#ffffff', league: 'EN' },
    { name: 'Norwich City', att: 1, opp: 3, def: 2, color1: '#fff200', color2: '#00a650', league: 'EN' },
    { name: 'Southampton', att: 1, opp: 3, def: 2, color1: '#cb3524', color2: '#ffffff', league: 'EN' },
    { name: 'Middlesbrough', att: 1, opp: 3, def: 2, color1: '#e30613', color2: '#ffffff', league: 'EN' },
    { name: 'Coventry City', att: 2, opp: 2, def: 3, color1: '#87ceeb', color2: '#ffffff', league: 'EN' },
    { name: 'Hull City', att: 3, opp: 2, def: 2, color1: '#f5a12d', color2: '#000000', league: 'EN' },
    { name: 'Watford', att: 1, opp: 3, def: 2, color1: '#fbee21', color2: '#ed2127', league: 'EN' },
    { name: 'Bristol City', att: 2, opp: 2, def: 2, color1: '#e30613', color2: '#ffffff', league: 'EN' },
    { name: 'Swansea City', att: 2, opp: 3, def: 1, color1: '#ffffff', color2: '#000000', league: 'EN' },
    { name: 'Preston NE.', att: 1, opp: 2, def: 3, color1: '#ffffff', color2: '#000040', league: 'EN' },
    { name: 'QPR', att: 1, opp: 3, def: 2, color1: '#ffffff', color2: '#0033a0', league: 'EN' },
    { name: 'Stoke City', att: 1, opp: 2, def: 3, color1: '#e30613', color2: '#ffffff', league: 'EN' },
    { name: 'Sheffield Wed', att: 1, opp: 2, def: 3, color1: '#0033a0', color2: '#ffffff', league: 'EN' },
    { name: 'Blackburn', att: 1, opp: 3, def: 2, color1: '#0033a0', color2: '#ffffff', league: 'EN' },
    { name: 'Millwall', att: 1, opp: 2, def: 3, color1: '#000040', color2: '#ffffff', league: 'EN' },
    { name: 'Derby County', att: 1, opp: 3, def: 2, color1: '#ffffff', color2: '#000000', league: 'EN' }
  ],
  IT: [
    { name: 'Monza', att: 3, opp: 2, def: 2, color1: '#ffffff', color2: '#cb3524', league: 'IT' },
    { name: 'Frosinone', att: 2, opp: 2, def: 3, color1: '#ffcc00', color2: '#0033a0', league: 'IT' },
    { name: 'Salernitana', att: 1, opp: 3, def: 2, color1: '#8b0000', color2: '#ffffff', league: 'IT' },
    { name: 'Sampdoria', att: 2, opp: 3, def: 1, color1: '#0033a0', color2: '#ffffff', league: 'IT' },
    { name: 'Palermo', att: 2, opp: 2, def: 2, color1: '#ffc0cb', color2: '#000000', league: 'IT' },
    { name: 'Venezia', att: 2, opp: 3, def: 2, color1: '#fb923c', color2: '#16a34a', league: 'IT' },
    { name: 'Brescia', att: 2, opp: 3, def: 1, color1: '#0033a0', color2: '#ffffff', league: 'IT' },
    { name: 'Bari', att: 1, opp: 3, def: 2, color1: '#ffffff', color2: '#e30613', league: 'IT' },
    { name: 'Empoli', att: 1, opp: 3, def: 2, color1: '#1e3a8a', color2: '#ffffff', league: 'IT' },
    { name: 'Spezia', att: 1, opp: 3, def: 2, color1: '#ffffff', color2: '#000000', league: 'IT' },
    { name: 'Catanzaro', att: 1, opp: 3, def: 2, color1: '#ffcc00', color2: '#e30613', league: 'IT' },
    { name: 'Reggiana', att: 1, opp: 2, def: 3, color1: '#8b0000', color2: '#ffffff', league: 'IT' },
    { name: 'Südtirol', att: 1, opp: 2, def: 3, color1: '#ffffff', color2: '#e30613', league: 'IT' },
    { name: 'Modena', att: 1, opp: 3, def: 2, color1: '#ffcc00', color2: '#0033a0', league: 'IT' },
    { name: 'Cosenza', att: 1, opp: 3, def: 2, color1: '#0033a0', color2: '#e30613', league: 'IT' },
    { name: 'Cittadella', att: 1, opp: 2, def: 3, color1: '#8b0000', color2: '#ffffff', league: 'IT' },
    { name: 'Mantova', att: 1, opp: 3, def: 2, color1: '#ffffff', color2: '#e30613', league: 'IT' },
    { name: 'Cesena', att: 2, opp: 2, def: 2, color1: '#ffffff', color2: '#000000', league: 'IT' },
    { name: 'Juve Stabia', att: 1, opp: 3, def: 2, color1: '#ffcc00', color2: '#0033a0', league: 'IT' },
    { name: 'Carrarese', att: 1, opp: 3, def: 2, color1: '#ffcc00', color2: '#0033a0', league: 'IT' }
  ],
  DE: [
    { name: 'VfL Bochum', att: 2, opp: 3, def: 1, color1: '#005ca9', color2: '#ffffff', league: 'DE' },
    { name: 'Darmstadt 98', att: 2, opp: 3, def: 1, color1: '#0033a0', color2: '#ffffff', league: 'DE' },
    { name: 'Holstein Kiel', att: 1, opp: 3, def: 2, color1: '#0053a4', color2: '#ffffff', league: 'DE' },
    { name: 'Hertha BSC', att: 2, opp: 3, def: 1, color1: '#0033a0', color2: '#ffffff', league: 'DE' },
    { name: 'Schalke 04', att: 2, opp: 3, def: 2, color1: '#0033a0', color2: '#ffffff', league: 'DE' },
    { name: 'Hannover 96', att: 1, opp: 3, def: 2, color1: '#e30613', color2: '#000000', league: 'DE' },
    { name: 'F. Düsseldorf', att: 2, opp: 3, def: 1, color1: '#e30613', color2: '#ffffff', league: 'DE' },
    { name: 'Karlsruher SC', att: 2, opp: 2, def: 2, color1: '#0033a0', color2: '#ffffff', league: 'DE' },
    { name: 'FC Nürnberg', att: 2, opp: 2, def: 2, color1: '#8b0000', color2: '#ffffff', league: 'DE' },
    { name: 'SC Paderborn', att: 3, opp: 2, def: 2, color1: '#000000', color2: '#0033a0', league: 'DE' },
    { name: 'Greuther Fürth', att: 1, opp: 3, def: 2, color1: '#00a650', color2: '#ffffff', league: 'DE' },
    { name: 'SV Elversberg', att: 2, opp: 2, def: 3, color1: '#ffffff', color2: '#000000', league: 'DE' },
    { name: 'FC Magdeburg', att: 1, opp: 3, def: 2, color1: '#0033a0', color2: '#ffffff', league: 'DE' },
    { name: 'E. Braunschweig', att: 1, opp: 2, def: 3, color1: '#ffcc00', color2: '#0033a0', league: 'DE' },
    { name: 'Kaiserslautern', att: 2, opp: 2, def: 2, color1: '#e30613', color2: '#ffffff', league: 'DE' },
    { name: 'SSV Ulm', att: 1, opp: 2, def: 3, color1: '#000000', color2: '#ffffff', league: 'DE' },
    { name: 'Essen', att: 2, opp: 3, def: 1, color1: '#ffffff', color2: '#e30613', league: 'DE' },
    { name: 'Jahn Regensburg', att: 1, opp: 2, def: 3, color1: '#ffffff', color2: '#e30613', league: 'DE' }
  ],
  FR: [
    { name: 'Clermont Foot', att: 1, opp: 2, def: 3, color1: '#e30613', color2: '#0033a0', league: 'FR' },
    { name: 'Valenciennes FC', att: 2, opp: 3, def: 1, color1: '#e30613', color2: '#ffffff', league: 'FR' },
    { name: 'Chamois Niortais', att: 1, opp: 3, def: 2, color1: '#ffcc00', color2: '#006400', league: 'FR' },
    { name: 'Stade Reims', att: 3, opp: 2, def: 2, color1: '#e30613', color2: '#ffffff', league: 'FR' },
    { name: 'Rodez AF', att: 1, opp: 3, def: 2, color1: '#e30613', color2: '#ffcc00', league: 'FR' },
    { name: 'SM Caen', att: 1, opp: 3, def: 2, color1: '#0033a0', color2: '#e30613', league: 'FR' },
    { name: 'EA Guingamp', att: 2, opp: 2, def: 2, color1: '#e30613', color2: '#000000', league: 'FR' },
    { name: 'Amiens SC', att: 2, opp: 3, def: 1, color1: '#ffffff', color2: '#000000', league: 'FR' },
    { name: 'SC Bastia', att: 2, opp: 3, def: 1, color1: '#0033a0', color2: '#ffffff', league: 'FR' },
    { name: 'Pau FC', att: 2, opp: 3, def: 1, color1: '#ffcc00', color2: '#0033a0', league: 'FR' },
    { name: 'Grenoble Foot', att: 2, opp: 2, def: 2, color1: '#0033a0', color2: '#ffffff', league: 'FR' },
    { name: 'FC Annecy', att: 1, opp: 3, def: 2, color1: '#e30613', color2: '#ffffff', league: 'FR' },
    { name: 'ES Troyes AC', att: 1, opp: 3, def: 2, color1: '#0033a0', color2: '#ffffff', league: 'FR' },
    { name: 'AC Ajaccio', att: 1, opp: 2, def: 3, color1: '#ffffff', color2: '#e30613', league: 'FR' },
    { name: 'USL Dunkerque', att: 1, opp: 3, def: 2, color1: '#87ceeb', color2: '#ffffff', league: 'FR' },
    { name: 'Red Star FC', att: 1, opp: 3, def: 2, color1: '#00a650', color2: '#ffffff', league: 'FR' },
    { name: 'Saint-Étienne', att: 2, opp: 3, def: 2, color1: '#006532', color2: '#ffffff', league: 'FR' },
    { name: 'Montpellier', att: 2, opp: 2, def: 3, color1: '#0033a0', color2: '#f68712', league: 'FR' }
  ],
  NL: [
    { name: 'Willem II', att: 2, opp: 2, def: 2, color1: '#ff0000', color2: '#ffffff', league: 'NL' },
    { name: 'Vitesse', att: 1, opp: 3, def: 2, color1: '#ffcc00', color2: '#000000', league: 'NL' },
    { name: 'Almere City', att: 1, opp: 3, def: 2, color1: '#ff0000', color2: '#000000', league: 'NL' },
    { name: 'De Graafschap', att: 2, opp: 3, def: 1, color1: '#0033a0', color2: '#ffffff', league: 'NL' },
    { name: 'ADO Den Haag', att: 2, opp: 2, def: 2, color1: '#00a650', color2: '#ffcc00', league: 'NL' },
    { name: 'SC Cambuur', att: 1, opp: 3, def: 2, color1: '#ffcc00', color2: '#0033a0', league: 'NL' },
    { name: 'FC Emmen', att: 2, opp: 3, def: 1, color1: '#e30613', color2: '#ffffff', league: 'NL' },
    { name: 'Roda JC', att: 1, opp: 3, def: 2, color1: '#ffcc00', color2: '#000000', league: 'NL' },
    { name: 'MVV Maastricht', att: 1, opp: 3, def: 2, color1: '#e30613', color2: '#ffffff', league: 'NL' },
    { name: 'VVV-Venlo', att: 2, opp: 3, def: 1, color1: '#ffcc00', color2: '#000000', league: 'NL' },
    { name: 'FC Dordrecht', att: 1, opp: 3, def: 2, color1: '#00a650', color2: '#ffffff', league: 'NL' },
    { name: 'Helmond Sport', att: 1, opp: 2, def: 3, color1: '#e30613', color2: '#000000', league: 'NL' },
    { name: 'FC Eindhoven', att: 2, opp: 3, def: 1, color1: '#0033a0', color2: '#ffffff', league: 'NL' },
    { name: 'RKC Waalwijk', att: 1, opp: 3, def: 2, color1: '#ffff00', color2: '#1e3a8a', league: 'NL' },
    { name: 'TOP Oss', att: 1, opp: 2, def: 3, color1: '#e30613', color2: '#ffffff', league: 'NL' },
    { name: 'FC Den Bosch', att: 2, opp: 3, def: 1, color1: '#0033a0', color2: '#ffffff', league: 'NL' },
    { name: 'Jong Ajax', att: 2, opp: 3, def: 1, color1: '#ffffff', color2: '#e30613', league: 'NL' },
    { name: 'Jong PSV', att: 2, opp: 3, def: 1, color1: '#ff0000', color2: '#ffffff', league: 'NL' }
  ],
  MI: [
    { name: 'Hajduk Split', att: 2, opp: 3, def: 3, color1: '#ffffff', color2: '#0033a0', league: 'MI' },
    { name: 'Hearts FC', att: 2, opp: 2, def: 3, color1: '#8b0000', color2: '#ffffff', league: 'MI' },
    { name: 'Boavista FC', att: 2, opp: 2, def: 3, color1: '#000000', color2: '#ffffff', league: 'MI' },
    { name: 'Başakşehir', att: 2, opp: 3, def: 2, color1: '#f36c21', color2: '#002d72', league: 'MI' },
    { name: 'Hibernian FC', att: 2, opp: 3, def: 2, color1: '#006532', color2: '#ffffff', league: 'MI' },
    { name: 'Legia Warsaw', att: 2, opp: 3, def: 2, color1: '#ffffff', color2: '#000000', league: 'MI' },
    { name: 'FC Midtjylland', att: 2, opp: 3, def: 2, color1: '#000000', color2: '#e30613', league: 'MI' },
    { name: 'Rio Ave FC', att: 2, opp: 2, def: 2, color1: '#006532', color2: '#ffffff', league: 'MI' },
    { name: 'Antalyaspor', att: 2, opp: 2, def: 2, color1: '#e30613', color2: '#ffffff', league: 'MI' },
    { name: 'KV Mechelen', att: 2, opp: 2, def: 2, color1: '#ffd700', color2: '#e30613', league: 'MI' },
    { name: 'Rosenborg', att: 2, opp: 2, def: 2, color1: '#ffffff', color2: '#000000', league: 'MI' },
    { name: 'Austria Viena', att: 2, opp: 2, def: 2, color1: '#542f88', color2: '#ffffff', league: 'MI' },
    { name: 'Qarabag FK', att: 2, opp: 2, def: 2, color1: '#000000', color2: '#ffffff', league: 'MI' },
    { name: 'Kilmarnock FC', att: 1, opp: 3, def: 2, color1: '#0033a0', color2: '#ffffff', league: 'MI' },
    { name: 'Maccabi Tel Aviv', att: 1, opp: 3, def: 2, color1: '#ffd700', color2: '#0033a0', league: 'MI' },
    { name: 'Charleroi', att: 1, opp: 2, def: 3, color1: '#000000', color2: '#ffffff', league: 'MI' },
    { name: 'Estoril Praia', att: 2, opp: 2, def: 1, color1: '#ffd700', color2: '#0033a0', league: 'MI' },
    { name: 'Motherwell FC', att: 1, opp: 2, def: 2, color1: '#8b0000', color2: '#ffd700', league: 'MI' }
  ],
  MB: [
    { name: 'Ferencváros', att: 2, opp: 3, def: 3, color1: '#00a650', color2: '#ffffff', league: 'MB' },
    { name: 'Rapid Viena', att: 2, opp: 2, def: 3, color1: '#006532', color2: '#ffffff', league: 'MB' },
    { name: 'Samsunspor', att: 2, opp: 2, def: 3, color1: '#e30613', color2: '#ffffff', league: 'MB' },
    { name: 'Standard Liège', att: 2, opp: 3, def: 2, color1: '#e30613', color2: '#ffffff', league: 'MB' },
    { name: 'Partizan', att: 2, opp: 3, def: 2, color1: '#000000', color2: '#ffffff', league: 'MB' },
    { name: 'Ludogorets', att: 2, opp: 3, def: 2, color1: '#00a650', color2: '#ffffff', league: 'MB' },
    { name: 'Brondby IF', att: 2, opp: 3, def: 2, color1: '#ffd700', color2: '#0033a0', league: 'MB' },
    { name: 'Famalicão', att: 2, opp: 2, def: 2, color1: '#0033a0', color2: '#ffffff', league: 'MB' },
    { name: 'Sivasspor', att: 2, opp: 2, def: 2, color1: '#e30613', color2: '#ffffff', league: 'MB' },
    { name: 'Servette FC', att: 2, opp: 2, def: 2, color1: '#8b0000', color2: '#ffffff', league: 'MB' },
    { name: 'FC Zürich', att: 2, opp: 2, def: 2, color1: '#ffffff', color2: '#0033a0', league: 'MB' },
    { name: 'Lech Poznań', att: 2, opp: 2, def: 2, color1: '#0033a0', color2: '#ffffff', league: 'MB' },
    { name: 'Cercle Brugge', att: 2, opp: 3, def: 1, color1: '#006532', color2: '#000000', league: 'MB' },
    { name: 'Dundee United', att: 1, opp: 3, def: 2, color1: '#f68712', color2: '#000000', league: 'MB' },
    { name: 'Gil Vicente', att: 1, opp: 2, def: 3, color1: '#e30613', color2: '#0033a0', league: 'MB' },
    { name: 'HNK Rijeka', att: 1, opp: 2, def: 3, color1: '#ffffff', color2: '#0033a0', league: 'MB' },
    { name: 'AIK Estocolmo', att: 1, opp: 2, def: 2, color1: '#000000', color2: '#ffd700', league: 'MB' },
    { name: 'Sheriff Tiraspol', att: 1, opp: 2, def: 2, color1: '#ffd700', color2: '#000000', league: 'MB' }
  ]
};

export const DERBY_PAIRS: { teams: [string, string]; name: string; emoji: string; intensity: number }[] = [
  // España
  { teams: ['Real Madrid', 'FC Barcelona'], name: 'El Clásico', emoji: '🔥', intensity: 5 },
  { teams: ['Real Madrid', 'Atlético Madrid'], name: 'Derby de Madrid', emoji: '⚔️', intensity: 5 },
  { teams: ['FC Barcelona', 'Espanyol'], name: 'Derby Catalán', emoji: '🏟️', intensity: 4 },
  { teams: ['Sevilla FC', 'Real Betis'], name: 'Gran Derbi de Sevilla', emoji: '💚❤️', intensity: 5 },
  { teams: ['Real Sociedad', 'Athletic Club'], name: 'Derby Vasco', emoji: '🔴🔵', intensity: 5 },
  { teams: ['Valencia CF', 'Villarreal CF'], name: 'Derby de la Comunitat', emoji: '🍊', intensity: 3 },
  { teams: ['Celta Vigo', 'Dep. La Coruña'], name: 'Derby Gallego', emoji: '🌊', intensity: 4 },
  { teams: ['Real Oviedo', 'Sporting Gijón'], name: 'Derby Asturiano', emoji: '⛰️', intensity: 5 },
  // Italia
  { teams: ['Inter Milan', 'AC Milan'], name: 'Derby della Madonnina', emoji: '🏛️', intensity: 5 },
  { teams: ['AS Roma', 'Lazio'], name: 'Derby della Capitale', emoji: '🐺🦅', intensity: 5 },
  { teams: ['Juventus', 'Inter Milan'], name: 'Derby d\'Italia', emoji: '🇮🇹', intensity: 5 },
  { teams: ['Juventus', 'Torino'], name: 'Derby della Mole', emoji: '🏔️', intensity: 5 },
  { teams: ['Genoa', 'Sampdoria'], name: 'Derby della Lanterna', emoji: '🏮', intensity: 4 },
  { teams: ['Napoli', 'Juventus'], name: 'Il Grande Classico', emoji: '⚡', intensity: 4 },
  // Inglaterra
  { teams: ['Liverpool FC', 'Man United'], name: 'Northwest Derby', emoji: '🔴', intensity: 5 },
  { teams: ['Manchester City', 'Man United'], name: 'Manchester Derby', emoji: '🏙️', intensity: 5 },
  { teams: ['Arsenal FC', 'Tottenham'], name: 'North London Derby', emoji: '🏟️', intensity: 5 },
  { teams: ['Liverpool FC', 'Everton'], name: 'Merseyside Derby', emoji: '🔵🔴', intensity: 5 },
  { teams: ['Chelsea FC', 'Arsenal FC'], name: 'London Rivalry', emoji: '🇬🇧', intensity: 4 },
  { teams: ['Chelsea FC', 'Tottenham'], name: 'London Derby', emoji: '💙🤍', intensity: 4 },
  { teams: ['Newcastle', 'Sunderland'], name: 'Tyne-Wear Derby', emoji: '⚫⬜', intensity: 5 },
  { teams: ['Leeds United', 'Man United'], name: 'Roses Rivalry', emoji: '🌹', intensity: 5 },
  // Alemania
  { teams: ['Bayern Munich', 'B. Dortmund'], name: 'Der Klassiker', emoji: '🇩🇪', intensity: 5 },
  { teams: ['B. Dortmund', 'Schalke 04'], name: 'Revierderby', emoji: '⛏️', intensity: 5 },
  { teams: ['Bayern Munich', 'B. Leverkusen'], name: 'TopSpiel', emoji: '🔝', intensity: 4 },
  { teams: ['Werder Bremen', 'Hamburger SV'], name: 'Nordderby', emoji: '🌊', intensity: 4 },
  // Francia
  { teams: ['PSG', 'Marseille'], name: 'Le Classique', emoji: '🇫🇷', intensity: 5 },
  { teams: ['Olympique Lyon', 'Saint-Étienne'], name: 'Derby Rhône-Alpes', emoji: '🦁', intensity: 5 },
  { teams: ['Olympique Lyon', 'Marseille'], name: 'Olympique Clásico', emoji: '🏛️', intensity: 4 },
  { teams: ['RC Lens', 'Lille OSC'], name: 'Derby du Nord', emoji: '🏗️', intensity: 4 },
  // Holanda
  { teams: ['Ajax', 'Feyenoord'], name: 'De Klassieker', emoji: '🇳🇱', intensity: 5 },
  { teams: ['Ajax', 'PSV Eindhoven'], name: 'De Topper', emoji: '🏆', intensity: 5 },
  { teams: ['Feyenoord', 'Sparta Rotterdam'], name: 'Stadsderby Rotterdam', emoji: '🏙️', intensity: 4 },
  // Portugal / Miscelánea
  { teams: ['Benfica', 'Sporting CP'], name: 'Derby de Lisboa', emoji: '🏟️', intensity: 5 },
  { teams: ['FC Porto', 'Benfica'], name: 'O Clássico', emoji: '🇵🇹', intensity: 5 },
  { teams: ['FC Porto', 'Sporting CP'], name: 'Clássico Lusitano', emoji: '🏛️', intensity: 4 },
  { teams: ['Celtic FC', 'Rangers FC'], name: 'Old Firm', emoji: '🏴', intensity: 5 },
  { teams: ['Galatasaray', 'Fenerbahçe'], name: 'Kıtalar Arası Derbi', emoji: '🇹🇷', intensity: 5 },
  { teams: ['Galatasaray', 'Beşiktaş'], name: 'Derby de Estambul', emoji: '🦅🦁', intensity: 5 },
  { teams: ['Fenerbahçe', 'Beşiktaş'], name: 'Derby del Bósforo', emoji: '🇹🇷', intensity: 5 },
  { teams: ['Olympiacos', 'Panathinaikos'], name: 'Derby de los Eternos', emoji: '🇬🇷', intensity: 5 },
  { teams: ['Olympiacos', 'PAOK'], name: 'Derby de Grecia', emoji: '⚡', intensity: 4 },
  { teams: ['Slavia Praga', 'Sparta Praga'], name: 'Derby de Praga', emoji: '🏰', intensity: 5 },
  { teams: ['Estrella Roja', 'Partizan'], name: 'Derby Eterno de Belgrado', emoji: '🔥', intensity: 5 },
  { teams: ['Dinamo Zagreb', 'Hajduk Split'], name: 'Vječni Derbi', emoji: '🇭🇷', intensity: 5 },
  { teams: ['Rapid Viena', 'Austria Viena'], name: 'Derby de Viena', emoji: '🇦🇹', intensity: 5 },
  { teams: ['Hearts FC', 'Hibernian FC'], name: 'Derby de Edimburgo', emoji: '🏰', intensity: 5 },
  { teams: ['FC Copenhague', 'Brøndby IF'], name: 'Derby de Copenhague', emoji: '🇩🇰', intensity: 5 },
  // Mundiales
  { teams: ['Argentina', 'Brazil'], name: 'Superclásico Sudamericano', emoji: '🌎', intensity: 5 },
  { teams: ['Argentina', 'England'], name: 'La Mano de Dios', emoji: '✋', intensity: 5 },
  { teams: ['Argentina', 'Germany'], name: 'Clásico Mundial', emoji: '🏆', intensity: 5 },
  { teams: ['Brazil', 'Germany'], name: 'Rivalidad Histórica', emoji: '⚽', intensity: 4 },
  { teams: ['France', 'Germany'], name: 'Le Classique Internacional', emoji: '🇪🇺', intensity: 4 },
  { teams: ['Spain', 'Italy'], name: 'Mediterráneo', emoji: '🌊', intensity: 4 },
  { teams: ['England', 'Germany'], name: 'Rivalidad Eterna', emoji: '🦁🦅', intensity: 5 },
  { teams: ['France', 'Argentina'], name: 'Final del Mundo', emoji: '🏆', intensity: 5 },
  { teams: ['Mexico', 'USA'], name: 'Clásico de CONCACAF', emoji: '🌮🗽', intensity: 5 },
  { teams: ['Brazil', 'Argentina'], name: 'Superclásico de las Américas', emoji: '🔥', intensity: 5 },
  { teams: ['Uruguay', 'Argentina'], name: 'Clásico del Río de la Plata', emoji: '🌊', intensity: 5 },
  { teams: ['Chile', 'Argentina'], name: 'Clásico Trasandino', emoji: '🏔️', intensity: 4 },
  { teams: ['Colombia', 'Argentina'], name: 'Clásico Suramericano', emoji: '☕', intensity: 3 },
];

export const findDerby = (teamName1: string, teamName2: string) => {
  return DERBY_PAIRS.find(d =>
    (d.teams[0] === teamName1 && d.teams[1] === teamName2) ||
    (d.teams[0] === teamName2 && d.teams[1] === teamName1)
  );
};
